### ISSUE TITLE
For compilations, Lastcast scrobbles with Album Artist rather than Track Artist

### ISSUE THREAD

**Issue by sti3** [erik/lastcast#37] opened 2018-02-16 16:43 UTC
It should scrobble the individual songs as Track Artist - Track Title.

![image](https://user-images.githubusercontent.com/35740/36318616-fac2e76c-1305-11e8-8ad8-e9a4374e7e67.png)

![image](https://user-images.githubusercontent.com/35740/36318669-2824ce6e-1306-11e8-97e2-48d484e372e1.png)

**Comment by erik** [comment] 2018-02-16 22:59
Hi @sti3, thanks for reporting the issue!

Looking briefly at the code, it should first try using the track artist, falling back to the album artist if that's not available. So my guess is that the tracks you're scrobbling are missing the track artist data?

https://github.com/erik/lastcast/blob/master/lastcast/__init__.py#L170

I'll dig into this deeper when I get a chance after the weekend.

**Comment by erik** [comment] 2018-02-21 05:05
Perhaps I'm misunderstanding the issue, but I'm unable to reproduce the behavior you described.

The following scrobbles as `Vincent Markowski - The Madness of Moths [DJ-Kicks: Apparat]` (using the track artist, not the album artist)

![screen shot 2018-02-20 at 21 00 43](https://user-images.githubusercontent.com/188935/36463848-449f79da-1681-11e8-93c8-a4bea58f59ac.png)

I'm not sure why it doesn't work that way for you as well. Could you show the track information?

**Comment by erik** [comment] 2018-03-06 22:13
Hi @sti3, any more info on this?

**Comment by erik** [comment] 2018-03-24 23:58
Going to close this out since I wasn't ever able to repro the issue, but please do reopen if this is still a problem!

**Closed as completed by erik** 2018-03-24 23:58 UTC
Labels: bug
