### ISSUE TITLE
File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve     raise DistributionNotFound(req) pkg_resources.DistributionNotFound: netifaces!=0.10.5

### ISSUE THREAD

**Issue by Katmassive** [erik/lastcast#36] opened 2018-01-30 19:27 UTC
lastcast --wizard
Traceback (most recent call last):
  File "/usr/local/bin/lastcast", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: netifaces!=0.10.5

**Comment by Katmassive** [comment] 2018-01-30 19:30
Installed pip install netifaces==0.10.4

> arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DNETIFACES_VERSION=0.10.4 -DHAVE_GETIFADDRS=1 -DHAVE_GETNAMEINFO=1 -DHAVE_NETASH_ASH_H=1 -DHAVE_NETATALK_AT_H=1 -DHAVE_NETAX25_AX25_H=1 -DHAVE_NETECONET_EC_H=1 -DHAVE_NETIPX_IPX_H=1 -DHAVE_NETPACKET_PACKET_H=1 -DHAVE_LINUX_IRDA_H=1 -DHAVE_LINUX_ATM_H=1 -DHAVE_LINUX_LLC_H=1 -DHAVE_LINUX_TIPC_H=1 -DHAVE_LINUX_DN_H=1 -DHAVE_SOCKADDR_AT=1 -DHAVE_SOCKADDR_AX25=1 -DHAVE_SOCKADDR_IN=1 -DHAVE_SOCKADDR_IN6=1 -DHAVE_SOCKADDR_IPX=1 -DHAVE_SOCKADDR_UN=1 -DHAVE_SOCKADDR_ASH=1 -DHAVE_SOCKADDR_EC=1 -DHAVE_SOCKADDR_LL=1 -DHAVE_SOCKADDR_ATMPVC=1 -DHAVE_SOCKADDR_ATMSVC=1 -DHAVE_SOCKADDR_DN=1 -DHAVE_SOCKADDR_IRDA=1 -DHAVE_SOCKADDR_LLC=1 -DHAVE_PF_NETLINK=1 -I/usr/include/python2.7 -c netifaces.c -o build/temp.linux-armv7l-2.7/netifaces.o

netifaces.c:1:20: fatal error: Python.h: No such file or directory

 #include <Python.h>

                    ^

compilation terminated.

error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/*********p-build-mQI0Wk/netifaces/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/*********p-rFIg63-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/*********p-build-mQI0Wk/netifaces
Storing debug log for failure in /home/*********/.pip/*********p.log

**Comment by erik** [comment] 2018-01-30 19:32
Hi @Katmassive, thanks for reporting the issue.

I believe `Python.h: No such file or directory` implies that you're missing the python dev package, which includes headers. If you're using debian (or raspbian, or ubuntu or ...), that would be `apt-get install python-dev`.

Could you try installing that and then rerunning `pip install --upgrade lastcast`?

**Comment by Katmassive** [comment] 2018-01-31 16:53
No luck.

~/raspberry-pi-gcc-binary $ lastcast --wizard
Traceback (most recent call last):
  File "/usr/local/bin/lastcast", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: enum34

**Comment by erik** [comment] 2018-01-31 17:26
Well, we've moved to a different error, so at least that's progress 🙂

This seems to be an error with your environment. Somehow you have missing upstream dependencies, since lastcast doesn't explicitly use the `enum34` package.

Let's try uninstalling all the packages lastcast depends on and then reinstalling. Could you run this command for me and show me the output?

```
sudo pip uninstall --yes pychromecast click pylast toml lastcast && \
sudo pip install --upgrade --no-cache-dir lastcast
```

**Comment by Katmassive** [comment] 2018-02-04 04:18
i was able to run: 

> sudo pip uninstall --yes pychromecast click pylast toml lastcast
> sudo pip install --upgrade lastcast
> 
> lastcast

returns:

> $ lastcast
> Traceback (most recent call last):
>   File "/usr/local/bin/lastcast", line 5, in <module>
>     from pkg_resources import load_entry_point
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
>     raise DistributionNotFound(req)
> pkg_resources.DistributionNotFound: enum34

went back manually emptied tmp 
re-ran commands. couldnt get the uninstall to run.

> 'Traceback (most recent call last):
>   File "/usr/bin/pip", line 9, in <module>
>     load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
>     ['__name__'])
>   File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
>     from pip.vcs import git, mercurial, subversion, bazaar  # noqa
>   File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
>     from pip.download import path_to_url
>   File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
>     from requests.compat import IncompleteRead
> ImportError: cannot import name IncompleteRead'

reboot the pi

> sudo pip uninstall --yes pychromecast click pylast toml lastcast
> Traceback (most recent call last):
>   File "/usr/bin/pip", line 9, in <module>
>     load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
>     ['__name__'])
>   File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
>     from pip.vcs import git, mercurial, subversion, bazaar  # noqa
>   File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
>     from pip.download import path_to_url
>   File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
>     from requests.compat import IncompleteRead
> ImportError: cannot import name IncompleteRead

> sudo pip install netifaces
> Traceback (most recent call last):
>   File "/usr/bin/pip", line 9, in <module>
>     load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
>     ['__name__'])
>   File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
>     from pip.vcs import git, mercurial, subversion, bazaar  # noqa
>   File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
>     from pip.download import path_to_url
>   File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
>     from requests.compat import IncompleteRead
> ImportError: cannot import name IncompleteRead

> sudo pip uninstall python2.7
> Traceback (most recent call last):
>   File "/usr/bin/pip", line 9, in <module>
>     load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
>     ['__name__'])
>   File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
>     from pip.vcs import git, mercurial, subversion, bazaar  # noqa
>   File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
>     from pip.download import path_to_url
>   File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
>     from requests.compat import IncompleteRead
> ImportError: cannot import name IncompleteRead
> 

> python -V
> Python 2.7.9

> 'sudo pip uninstall netifaces
> Traceback (most recent call last):
>   File "/usr/bin/pip", line 9, in <module>
>     load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
>     ['__name__'])
>   File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
>     from pip.vcs import git, mercurial, subversion, bazaar  # noqa
>   File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
>     from pip.download import path_to_url
>   File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
>     from requests.compat import IncompleteRead
> ImportError: cannot import name IncompleteRead'
> 
> sudo pip install netifaces==0.10.4
> Traceback (most recent call last):
>   File "/usr/bin/pip", line 9, in <module>
>     load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
>     ['__name__'])
>   File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
>     from pip.vcs import git, mercurial, subversion, bazaar  # noqa
>   File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
>     from pip.download import path_to_url
>   File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
>     from requests.compat import IncompleteRead
> ImportError: cannot import name IncompleteRead

maybe its python??

**Comment by erik** [comment] 2018-02-04 06:18
Hmm... I'm not sure what the issue is here, but it does seem unrelated to lastcast.

Maybe this StackOverflow answer is relevant? https://stackoverflow.com/a/27425458

**Comment by Katmassive** [comment] 2018-02-05 15:42
Awesome that worked. 

> sudo apt-get remove python-pip
> sudo easy_install pip
> sudo pip install enum34
> lastcast --wizard
> lastcast

Do I have to leave the terminal open?

**Comment by erik** [comment] 2018-02-05 16:33
Great, glad that worked for you!

So if you want to be able to close your terminal but keep the program running, you could either run `lastcast` in [screen](https://www.howtogeek.com/howto/ubuntu/keep-your-ssh-session-running-when-you-disconnect/) or [tmux](http://www.hamvocke.com/blog/a-quick-and-easy-guide-to-tmux/).

Or, a better solution, which would restart the process in case it crashed, would be to use something like systemd. I have instructions on setting that up in the README [here](https://github.com/erik/lastcast#linux--systemd-instructions).

Hope that helps!

**Comment by erik** [comment] 2018-02-05 23:35
I'm going to close this issue now since the original problem seems to be resolved (if it's not feel free to reopen 🙂 ).

If you run into any other problems please let me know!

**Closed as completed by erik** 2018-02-05 23:35 UTC
